### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by stacycurl** [stacycurl/pimpathon#197]
I do this so infrequently I'm leaving copious notes for my future self.

Update version (drop snapshot)
Update ReleaseNotes-1.5.0 (drop snapshot)
Create ReleaseNotes-1.6.0
Update readme
git commit -m "Released 1.5.0"
git tag 1.5.0
sbt ++2.10.4 clean publishedSigned
sbt ++2.11.2 clean publishedSigned
git checkout 2.9
git merge master
git tag 1.5.0-2.9
sbt ++2.9.2 clean publishedSigned
sbt ++2.9.3 clean publishedSigned
Sonatype voodoo
git checkout master
git push --all

**Comment by fommil** [comment]
yeah, the fact that sbt-release is broken right now is a real PITA

**Comment by fommil** [comment]
any chance of doing this soon? My ENSIME WIP is using your 1.5.0-SNAPSHOT and I was thinking about raising a PR this weekend.

**Comment by fommil** [comment]
btw, you know there is a new multi-scala version feature in the latest sbt? One branch, multiple scala builds (separate directories roots for different scala versions, and a common one).

**Comment by stacycurl** [comment]
Sorry about the delay, I'll get to this tomorrow.

On 8 May 2015 at 13:29, Sam Halliday <notifications@github.com> wrote:

> btw, you know there is a new multi-scala version feature in the latest
> sbt? One branch, multiple scala builds (separate directories roots for
> different scala versions, and a common one).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stacycurl/pimpathon/issues/197#issuecomment-100217936>
> .
>



-- 
Stacy

**Comment by stacycurl** [comment]
Hmm, having some trouble with this (pom files had duplicate elements,
missing asc files), will continue tinkering.

On 8 May 2015 at 20:29, Stacy Curl <stacy.curl@gmail.com> wrote:

> Sorry about the delay, I'll get to this tomorrow.
>
> On 8 May 2015 at 13:29, Sam Halliday <notifications@github.com> wrote:
>
>> btw, you know there is a new multi-scala version feature in the latest
>> sbt? One branch, multiple scala builds (separate directories roots for
>> different scala versions, and a common one).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/stacycurl/pimpathon/issues/197#issuecomment-100217936>
>> .
>>
>
>
>
> --
> Stacy
>



-- 
Stacy

**Comment by stacycurl** [comment]
Ok released.

On 10 May 2015 at 16:00, Stacy Curl <stacy.curl@gmail.com> wrote:

> Hmm, having some trouble with this (pom files had duplicate elements,
> missing asc files), will continue tinkering.
>
> On 8 May 2015 at 20:29, Stacy Curl <stacy.curl@gmail.com> wrote:
>
>> Sorry about the delay, I'll get to this tomorrow.
>>
>> On 8 May 2015 at 13:29, Sam Halliday <notifications@github.com> wrote:
>>
>>> btw, you know there is a new multi-scala version feature in the latest
>>> sbt? One branch, multiple scala builds (separate directories roots for
>>> different scala versions, and a common one).
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/stacycurl/pimpathon/issues/197#issuecomment-100217936>
>>> .
>>>
>>
>>
>>
>> --
>> Stacy
>>
>
>
>
> --
> Stacy
>



-- 
Stacy

**Comment by fommil** [comment]
Thanks!
