### ISSUE TITLE
File.canon

### ISSUE THREAD

**Issue by stacycurl** [stacycurl/pimpathon#198]
Nab from ensime

**Comment by fommil** [comment]
heh, actually I was considering asking for this

**Comment by fommil** [comment]
if this were in a 1.4.x release, might tempt me to use jcenter :smiling_imp:

**Comment by stacycurl** [comment]
Deal, I'll do it tomorrow.

On 24 April 2015 at 20:43, Sam Halliday <notifications@github.com> wrote:

> if this were in a 1.4.x release, might tempt me to use jcenter [image:
> :smiling_imp:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stacycurl/pimpathon/issues/198#issuecomment-96044271>.
>



-- 
Stacy

**Comment by fommil** [comment]
sweet
