### ISSUE TITLE
Numeric.boundedInclusive(lower, upper) (and excl)

### ISSUE THREAD

**Issue by fommil** [stacycurl/pimpathon#203]
it would be great to be able to write

```scala
num.boundedInclusive(10, 100)
```

instead of the confusing (backward feeling)

```scala
(10 max num) min 100
```

**Comment by stacycurl** [comment]
What do you expect boundedExclusive to be defined as ? boundedInclusive(lower + one, upper - one) ?
(with '+', '-', and 'one' coming from Numeric).

**Comment by fommil** [comment]
come into my web, said the spider... http://www.amazon.co.uk/Introduction-Metric-Topological-Spaces-Mathematics/dp/019956308X

**Comment by fommil** [comment]
hehe, but back to the ticket... perhaps having an "exclusive" bounded just confuses things. The user can always calculate inclusive bounds. That might mean that `bounded` is a good name for the method.

**Comment by fommil** [comment]
hmm, this does open up the possibility of creating a method with that great Scottish word "outwith".
