### ISSUE TITLE
no 1.3.0 tag

### ISSUE THREAD

**Issue by fommil** [stacycurl/pimpathon#204]
looks like you forgot to tag the release

**Comment by stacycurl** [comment]
Sorry, I had created them locally, didn't realise they hadn't been automatically pushed.

**Comment by dwijnand** [comment]
I know the feeling, FWIW (I always forget myself but..) there's a `--follow-tags` in push, so:

    git push --follow-tags

after a release

**Comment by stacycurl** [comment]
Thanks Dale but I think i have a solution that doesn't require remembering
anything.

http://stackoverflow.com/questions/2988088/do-git-tags-get-pushed-as-well

... Alternatively you can configure the remote you push to to always push
all tags, e.g. put something like that in your .git/config:

[remote "publish"] # or whatever it is named
    url = ...
    push = +refs/heads/*:refs/heads/*
    push = +refs/tags/*:refs/tags/*

This means force push all heads (all branches) and all tags (if you don't
want force pushing of heads, remove '+' prefix from refspec). ...



On 17 March 2015 at 11:04, Dale Wijnand <notifications@github.com> wrote:

> I know the feeling, FWIW (I always forget myself but..) there's a
> --follow-tags in push, so:
>
> git push --follow-tags
>
> after a release
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stacycurl/pimpathon/issues/204#issuecomment-82281018>.
>



-- 
Stacy
