### ISSUE TITLE
Add List[A].zipExact(List[B]): (List[(A, B)], List[A], List[B])

### ISSUE THREAD

**Issue by stacycurl** [stacycurl/pimpathon#207]
List(1, 2, 3).zip(List(4, 5, 6)) == (List((1, 4), (2, 5), (3, 6)), Nil, Nil)
List(1).zip(List(4, 5, 6)) == (List((1, 4)), Nil, List(5, 6))
List(1, 2, 3).zip(List(4)) == (List((1, 4)), List(2, 3), Nil)

**Comment by stacycurl** [comment]
Signature could be 
List[A].zipExact(List[B]): (List[(A, B)], Option[Either[List[A], List[B]]])

**Comment by stacycurl** [comment]
Done in 1.4.5

**Comment by fommil** [comment]
huh?

**Comment by fommil** [comment]
aaah, three parts in response. Unmatched components.

**Comment by stacycurl** [comment]
Yeah, it's quite ugly, as types go.

On 25 April 2015 at 00:13, Sam Halliday <notifications@github.com> wrote:

> aaah, three parts in response. Unmatched components.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stacycurl/pimpathon/issues/207#issuecomment-96093455>.
>



-- 
Stacy

**Comment by fommil** [comment]
I have lost all rights to complain about type signatures https://github.com/fommil/ensime-server/blob/jerk/jerk/src/main/scala/org/ensime/jerk/FamilyFormats.scala#L126

**Comment by fommil** [comment]
this one, possibly worse https://github.com/fommil/ensime-server/blob/jerk/jerk/src/main/scala/org/ensime/jerk/FamilyFormats.scala#L177
