### ISSUE TITLE
Add jcenter resolver to docs

### ISSUE THREAD

**Issue by stacycurl** [stacycurl/pimpathon#214]

**Comment by fommil** [comment]
jcenter is not mirrored by the standard sbt resolvers (which include maven central and a typesafe one, if I recall correctly) which means we cannot use pimpathon jcenter releases in ENSIME :cry: because we rely on a basic `sbt` deploy environment for end users and adding an additional resolver will make it very difficult for some corporate users.

**Comment by stacycurl** [comment]
Pity.

Hmm, I've read somewhere that jcenter might publish to maven, but I can't
see 1.4.x releases there, maybe there's something I need to do.

I'm getting annoying failings publishing to bintray; seems that they have a
rate limit, or serial publishing requirement; when I push all branches
travis kicks off 4 builds and thus publishing 4 versions in parallel; this
often fails. When I re-run them individually it succeeds. I have to clean
up the half-published crap beforehand, it's more hassle than sonatype, ffs.

The whole point of using bintray was to make publishing simple; if I can't
get that to work I may return to sonatype, I'd still want to find some way
of automating things though.

On 25 April 2015 at 16:11, Sam Halliday <notifications@github.com> wrote:

> jcenter is not mirrored by the standard sbt resolvers (which include maven
> central and a typesafe one, if I recall correctly) which means we cannot
> use pimpathon jcenter releases in ENSIME [image: :cry:] because we rely
> on a basic sbt deploy environment for end users and adding an additional
> resolver will make it very difficult for some corporate users.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stacycurl/pimpathon/issues/214#issuecomment-96220553>.
>



-- 
Stacy

**Comment by fommil** [comment]
I know exactly what you mean. I found bintray to be a lot more frustrating than sonatype... just I just gave up. I'm actually happy with `SNAPSHOT`s on sonatype and irregular final releases on central. If you have a feature that you're going to release soon, I'm happy using SNAPSHOTs in my dev branch until you release.

**Comment by fommil** [comment]
I think you can automate everything to do with sonatype except for the "press the button to close/release" bit. I'm actually happy with that because it saves me doing anything stupid.

**Comment by stacycurl** [comment]
Anyhow by my reckoning it's been over 2 months since a 1.x.0 release, I'll
get 1.5.0 published to sonatype tomorrow.

On 25 April 2015 at 16:18, Stacy Curl <stacy.curl@gmail.com> wrote:

> Pity.
>
> Hmm, I've read somewhere that jcenter might publish to maven, but I can't
> see 1.4.x releases there, maybe there's something I need to do.
>
> I'm getting annoying failings publishing to bintray; seems that they have
> a rate limit, or serial publishing requirement; when I push all branches
> travis kicks off 4 builds and thus publishing 4 versions in parallel; this
> often fails. When I re-run them individually it succeeds. I have to clean
> up the half-published crap beforehand, it's more hassle than sonatype, ffs.
>
> The whole point of using bintray was to make publishing simple; if I can't
> get that to work I may return to sonatype, I'd still want to find some way
> of automating things though.
>
> On 25 April 2015 at 16:11, Sam Halliday <notifications@github.com> wrote:
>
>> jcenter is not mirrored by the standard sbt resolvers (which include
>> maven central and a typesafe one, if I recall correctly) which means we
>> cannot use pimpathon jcenter releases in ENSIME [image: :cry:] because
>> we rely on a basic sbt deploy environment for end users and adding an
>> additional resolver will make it very difficult for some corporate users.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/stacycurl/pimpathon/issues/214#issuecomment-96220553>
>> .
>>
>
>
>
> --
> Stacy
>



-- 
Stacy

**Comment by fommil** [comment]
sweet. can you do a 1.5.0-SNAPSHOT in the meantime?

**Comment by stacycurl** [comment]
Done.

On 25 April 2015 at 16:35, Sam Halliday <notifications@github.com> wrote:

> sweet. can you do a 1.5.0-SNAPSHOT in the meantime?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stacycurl/pimpathon/issues/214#issuecomment-96225576>.
>



-- 
Stacy

**Comment by fommil** [comment]
cool! I'll start using it now
