### ISSUE TITLE
Upgrade [master] to java 1.7 

### ISSUE THREAD

**Issue by stacycurl** [stacycurl/pimpathon#222]

**Comment by stacycurl** [comment]
@fommil Any thoughts on this, would this break stuff for you ? (echo echo ...)

**Comment by fommil** [comment]
yup, sorry, we need java 6 support

**Comment by fommil** [comment]
once we release ENSIME 1.0 we're moving to Java 7 so won't be long.

**Comment by stacycurl** [comment]
No worries, I'll chuck it into a backlog until then.
