### ISSUE TITLE
Upgrade [2.9] to java 1.7

### ISSUE THREAD

**Issue by stacycurl** [stacycurl/pimpathon#223]

**Comment by stacycurl** [comment]
@fommil Any thoughts on this, would this break stuff for you ?

**Comment by fommil** [comment]
we're going to drop scala 2.9 when we release ENSIME 1.0 so from my perspective we won't be needing your releases past that anyway.

**Comment by stacycurl** [comment]
No worries, I'll chuck it into a backlog until then.
